export { default as AcelerometroScreen } from "./Acelerometro"
export { default as AudioVideoScreen } from "./AudioVideo"
export { default as GyroscopioScreen } from "./Gyroscopio"
export { default as MagnetoScreen } from "./Magneto"
export { default as PedometroScreen } from "./Pedometro"